### ISSUE TITLE
Wild Magic Surge Args fix

### ISSUE THREAD

**Issue by HWogi** [jfflbnntt/roll20-api-scripts#3]
Greetings, thank you for the wonderful scripts. My group and I attempted to use your wild magic surge tables in whispers and found that using any argument while executing !wildmagic would always result in a public wild magic table roll. Arguments --help, --private, -h, and -w would all default to the regular use of !wildmagic. 

We edited lines 91 to 101 of the script and got it to work by replacing them with this:
[WMSfix.txt](https://github.com/jfflbnntt/roll20-api-scripts/files/493875/WMSfix.txt)

```
switch(args[0]) {
            case apiCommand:
                var isPrivate = false;
                var sendMessage;
                if (args.length > 1) {
                    if (args[1] == "--help" || args[1] == "-h") {
                        sendChat(tableName, helpMsg);
                        return;
                    }
                    else if(args[1] == "--private" || args[1] == "-w") {
                        var isPrivate = true;
```

**Comment by jfflbnntt** [comment]
Thanks! I reworked the args parsing based on your feedback and tested it. Seems to be working now. Glad to hear someone's using it. Cheers.
